apiVersion: apps/v1
kind: StatefulSet
metadata:
  creationTimestamp: null
  labels:
    app: schema-registry
  name: schema-registry
spec:
  serviceName: "schema-registry"
  replicas: 1
  selector:
    matchLabels:
      app: schema-registry
  template:
    metadata:
      labels:
        app: schema-registry
    spec:
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
      containers:
      - image: dwijad/schema-registry:latest
        name: schema-registry
    env:
    - name: SCHEMA_REGISTRY_JMX_PORT
      value: "8080"
    - name: SCHEMA_REGISTRY_JMX_ENABLED
      value: "1"
        resources:  
          requests:
            memory: "1Gi"
            cpu: "0.5"
        livenessProbe:
          httpGet:
            path: /
            port: 8081
          initialDelaySeconds: 25
          periodSeconds: 5
#      imagePullSecrets:
#        - name: regcred
